---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tetris
  template:
    metadata:
      labels:
        app: tetris
    spec:
      containers:
      - name: tetris
        image: shaikmustafa/dm
        ports:
        - containerPort: 80   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: tetris-svc
spec:
  selector:
    app: tetris
  ports:
    - port: 80                 # Expose port 80
    targetPort: 3000
  type: NodePort
